"""add_resume_phone

Revision ID: 05a0d55b23e3
Revises: cb925e62376d
Create Date: 2026-02-19 12:29:14.776397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05a0d55b23e3'
down_revision: Union[str, None] = 'cb925e62376d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('phone', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumes', 'phone')
    # ### end Alembic commands ###
