"""add_resume_profile_image

Revision ID: 3010e4d8d5c8
Revises: 05a0d55b23e3
Create Date: 2026-02-19 12:32:32.983271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3010e4d8d5c8'
down_revision: Union[str, None] = '05a0d55b23e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('profile_image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumes', 'profile_image_url')
    # ### end Alembic commands ###
