"""add_resume_status

Revision ID: cb925e62376d
Revises: c625e404dc2e
Create Date: 2026-02-19 11:51:45.410771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb925e62376d'
down_revision: Union[str, None] = 'c625e404dc2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('status', sa.String(), nullable=True))
    op.execute("UPDATE resumes SET status = 'UPLOADED'")
    op.alter_column('resumes', 'status', nullable=False)
    op.add_column('resumes', sa.Column('error_reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumes', 'error_reason')
    op.drop_column('resumes', 'status')
    # ### end Alembic commands ###
